### PR TITLE
Fixed Edit Habits to ignore edits to the Habit Title.

### LINKED ISSUE #27: Edit Habit to ignore changing Habit Title
Since the Habit title is used as a document ID in firestore, attempting to edit it will create a new Habit. Our view of a habit is the title is a unique identifier so editing it should be disallowed. Will look further into this if needed.

### LINKED ISSUE #32: Add copyright to project.
Added copyright profile that covers whole app.

### LINKED ISSUE #33: Added comments to source files and to public methods and classes.

### PR DESCRIPTION
**Pull request by marty-rudolf**
Close #27 Close #28 Close #32 Close #33 

Wontfix label is for this Milestone.

### CODE REVIEW

File: CMPUT301Project/app/src/main/java/com/example/GroupProject/EditHabitActivity.java [hunk 1]
```diff
@@ -80,7 +80,8 @@ protected void onCreate(Bundle savedInstanceState) {
             Map<String, Object> editHabit = new HashMap<>();
 
             // Add all these to Firestore
-            String habitTitle = etHabitTitle.getText().toString();
+//            String habitTitle = etHabitTitle.getText().toString();
+            String habitTitle = habit.getTitle();
```
Comment (schen32) [inline CMPUT301Project/app/src/main/java/com/example/GroupProject/EditHabitActivity.java:84]: There should be a way to make the habitTitle field uneditable instead of doing this. Try making the habitTitle field uneditable and keep everything else the same.

**Review by schen32 — APPROVED** [review]
